export {default as AdvancedFooter} from './footer/AdvancedFooter'
export {default as NavbarHeader} from './header/NavbarHeader'

export {default as HeroSection} from './sections/HeroSection'
export {default as IntroSection} from './sections/IntroSection'
export {default as ConnectSection} from './sections/ConnectSection'
export {default as AboutSection} from './sections/AboutSection'
export {default as HistorySection} from './sections/HistorySection'
export {default as PurificationSection} from './sections/PurificationSection'
export {default as MapSection} from './sections/MapSection'
export {default as NewsSection} from './sections/NewsSection'
