# https://help.github.com/en/articles/workflow-syntax-for-github-actions#name
name: Publish

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on: repository_dispatch

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobs
jobs:

  # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_id
  first_job:

    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
  
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
    
    # https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables
    # https://github.com/actions/checkout
    - uses: actions/checkout@v2
      with:
        path: '.'
    
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsid
    - name: Update dates.txt with new date

      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsenv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun
      run: |

        #if [[ -z $(git branch --list jaen-storage) ]]; then
        #    echo "There is no jaen-storage"
        #else
        #    # remove `jaen-storage` branch.
        #    git branch -d jaen-storage 2>/dev/null 
        #fi

        # ensure we're on the `jaen-storage` branch.
        git checkout --orphan  jaen-storage
        
        git rm -rf .
        
        # create or update `jaen-data.json`
        touch jaen-data.json
        
        # append the current datetime to the end of `jaen-data.json`
        echo '${{ toJson(github.event.client_payload) }}' >> jaen-data.json
        
        # reveal what `jaen-data.json` looks like in the logs
        cat jaen-data.json
        
        # Git: set identity
        git config --global user.name "snekmin"
        git config --global user.email "noreply.snek.at@gmail.com"
        
        # Git: set remote  
        # https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
  
        # Git: add, commit, and push changes
        git add jaen-data.json
        git commit -m "Update jaen-data.json"
        GIT_TRACE=1 git push -f --verbose origin jaen-storage
